-- https://en.wikipedia.org/wiki/Block_Elements
BLOCK_FULL = "\u{2588}"
BLOCK_BLANK = "\u{2003}"
BLOCK_SHADE_LIGHT = "\u{2591}"
-- BLOCK_SHADE_LIGHT = "\u{25A6}"
BLOCK_SHADE_MEDIUM = "\u{2592}"
BLOCK_SHADE_DARK = "\u{2593}"
BLOCK_SHADE_DARK = "\u{2610}"

-- U+2591 	░ 	Light shade
-- U+2592 	▒ 	Medium shade
-- U+2593 	▓ 	Dark shade

function block_char(char, rep, color)
    return "<color=" .. color .. ">" .. string.rep(char, rep) .. "</color>"
end
